### ISSUE TITLE
How to set interval

### ISSUE THREAD

**Issue by vijit-ail** [vydimitrov/use-elapsed-time#50]
How do I set interval on the elapsed time so that it only updates every second? Right now it is causing too many re-renders and I want to update only on each second.

**Comment by vydimitrov** [comment]
Hey, does this have any performance implications for you? It is not possible to change the update interval.

**Comment by vijit-ail** [comment]
Yes, I'm actually using it for a tracker on React Native, although I haven't tested on a real device my Simulator is taking up lot of CPU when I'm on this particular screen.

**Comment by vydimitrov** [comment]
How big is the component that consumes the hook? How much additional computation does it do?

**Comment by vijit-ail** [comment]
Component is relatively smaller.. but there are two elapsed time hooks involved, one hook tracks the total elasped time since start of the day.. and the second hooks is for the actual time tracking.. hope that makes sense..
Apart from the hooks.. there are a few sqlite queries.. but those are inside useEffect.. so shouldn't be a problem.

**Comment by vydimitrov** [comment]
I see ... the best I can think of is this:

```js
const ElapsedTime = ({ children }) => {
   const isPlaying = true
  const { elapsedTime } = useElapsedTime(isPlaying)
 
 return chilren({ elapsedTime: Math.floor(elapsedTime) }) // as function or clone element
}
```

```js
const ConsumeElapsedTime = ({ elasedTime }) => {
  // your code here
}

export default React.memo(ConsumeElapsedTime ) // this will make sure it rerenders only once every second
```
Use it like
```js
<ElapsedTime >
  {ConsumeElapsedTime }
</ElapsedTime >

```

**Comment by vijit-ail** [comment]
Thanks a lot. I'll try it out, this should do the trick.

**Comment by vydimitrov** [comment]
Cool, let me know how it goes

**Comment by vijit-ail** [comment]
Thanks for the prompt help. The component is very optimised now.
